name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{secrets.USER_EMAIL}}
          git config --global user.name ${{secrets.USER_NAME}}
          git remote set-url origin https://${{secrets.SECRET_TOKEN}}@github.com/sorryrobots/react_zero.git
          npm run deploy